name: Deploy to Github Pages

# Trigger the workflow when a commit is pushed to "source" branch
on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with submodules and full history
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true or recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Install the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2  # Keep the latest version compatible with Node 20
        with:
          hugo-version: 'latest'
          extended: true

      # Build the Hugo site
      - name: Build
        run: hugo mod clean
        run: hugo --minify

      # Deploy the built content to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4  # Update to the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main # Use 'main' or the branch you're deploying to
          publish_dir: ./public
